### ISSUE TITLE
Unable to upload on the WUD

### ISSUE THREAD

**Issue by etr450b** [tobozo/WUD-Ducky#19]
Hello,
I just received the April Brothers WUD (ESP32-S2) and tried to flash this repo on it.
So far I downloaded all dependencies, select 'ESP32-S2 Dev Module' Board and was able to verify the 'WUD-Ducky.ino'.

However when I try to upload it on the WUD, I get this error message : 

```
Sketch uses 953934 bytes (72%) of program storage space. Maximum is 1310720 bytes.
Global variables use 57208 bytes (17%) of dynamic memory, leaving 270472 bytes for local variables. Maximum is 327680 bytes.
esptool.py v3.1
Serial port /dev/cu.Bluetooth-Incoming-Port
Connecting........_____....._____....._____....._____....._____....._____....._____

A fatal error occurred: Failed to connect to ESP32-S2: Timed out waiting for packet header
Failed uploading: uploading error: exit status 2 
```

I am not able to detect the WUD in DFU mode with `dfu-util -l` wether I'm pressing the RST button and applying a magnet on the ESP32-S2 module.

I'm running on a M1 Macbook Pro (Ventura 13.1).

Can you guys help me with what I'm doing wrong here ?

Thanks a lot and have a nice day !

**Comment by tobozo** [comment]
Hi, thanks for your feedback :+1: 

> Serial port /dev/cu.Bluetooth-Incoming-Port

`/dev/cu.Bluetooth-Incoming-Port` is not a UART port, so getting a fatal error is perfectly normal.

The [official documentation](https://wiki.aprbrother.com/en/wud.html#device-firmware-upgrade-through-usb) explains how the unit can be put in boot mode. I'm not sure why they don't mention the magnet (poke @aprilbrother) but their documentation should state that "pulling GPIO0 down" is just putting the magnet near the sensor, and "releasing GPIO0" is just taking it away.

When the operation is successful, a new serial port becomes available in arduino tool/ports menu.

Also don't forget to manually reset the esp32-wud after flashing otherwise it'll stay in download mode and just wait forever.

**Comment by etr450b** [comment]
Hi, thanks for you quick answer ! 
I tried putting the magnet, holding RST then removing it but it changes nothing...
The access point disappears but nothing is detected neither by Arduino or by dfu-util ?

I dont see any seial port available except wlan and bluetooth who were already presents before.

Running on Mac OS could be the isssue ? 

Thanks a lot,

**Comment by tobozo** [comment]
just keep on trying until it works, you'll eventually find the right position/sequence, it took me a while too :wink: 

I don't have a mac so I'm afraid I can't help you with troubleshooting that.

Now if it still doesn't work, please see with your seller as I'm only the maintainer of this project and this issue tracker is for problems with the code, not with the device.

closing this as out of scope
